# 43B GPT
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh nv_benefits_dragon_retriever300_retrieved_generic 43b greedy test 32 1e-6  0 250 472541 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-multi-1.1t-gtc/tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 32 1e-6  0 250 472541 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-multi-1.1t-gtc/tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh nq 43b greedy test  32 1e-6  0 200 472541 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-multi-1.1t-gtc/tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  32 1e-6  0 250 472541 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-multi-1.1t-gtc/tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  32 1e-6  0 250 472541 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-multi-1.1t-gtc/tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 472541 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-multi-1.1t-gtc/tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 32 1e-6  0 250 472541 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-multi-1.1t-gtc/tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh Iternal_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 472541 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-multi-1.1t-gtc/tp8pp1

#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh nv_benefits_dragon_retriever300_retrieved_generic 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-gpt-fitting-tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-gpt-fitting-tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh nq 43b greedy test  32 1e-6  0 200 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-gpt-fitting-tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-gpt-fitting-tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-gpt-fitting-tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-gpt-fitting-tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-gpt-fitting-tp8pp1
#bash examples/qa/generate_multijob_ckpt_step_same_format_short.sh Iternal_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-gpt-fitting-tp8pp1

## 43B Retro
#bash examples/qa/retro_generate_multijob_ckpt_step_same_format.sh nv_benefits_dragon_retriever300_retrieved_generic 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/qa/retro_generate_multijob_ckpt_step_same_format_short_reuse.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/qa/retro_generate_multijob_ckpt_step_same_format.sh nq 43b greedy test  32 1e-6  0 200 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/qa/retro_generate_multijob_ckpt_step_same_format.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/qa/retro_generate_multijob_ckpt_step_same_format.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/qa/retro_generate_multijob_ckpt_step_same_format.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/qa/retro_generate_multijob_ckpt_step_same_format.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/qa/retro_generate_multijob_ckpt_step_same_format.sh Iternal_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2


#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format.sh nv_benefits_dragon_retriever300_retrieved_generic 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format.sh nq 43b greedy test  32 1e-6  0 200 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format.sh Iternal_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2

#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh nv_benefits_dragon_retriever300_retrieved_generic 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh nq 43b greedy test  32 1e-6  0 200 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh Iternal_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2

#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh nv_benefits_dragon_retriever300_retrieved_generic 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh nq 43b greedy test  32 1e-6  0 200 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh Iternal_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 5 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh nv_benefits_dragon_retriever300_retrieved_generic 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh nq 43b greedy test  32 1e-6  0 200 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5
#bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh Iternal_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 5

bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh nv_benefits_dragon_retriever300_retrieved_generic 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh nq 43b greedy test  32 1e-6  0 200 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2
bash examples/foundational_qa/retro_generate_multijob_ckpt_step_same_format_reuse.sh Iternal_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 32 1e-6  0 250 32552 2 pp1 /lustre/fsw/adlr/adlr-nlp/boxinw/checkpoints/retro-nvllm/gpt3-43b-pretraining-retro-fitting-noseqpar-pp1-distributed 2