# FROM nvcr.io/nvidia/pytorch:24.01-py3
FROM nvcr.io/nvidia/nemo:24.01.framework

RUN pip install --no-cache-dir wandb nltk wrapt zarr tensorstore==0.1.45 git+https://github.com/fanshiqing/grouped_gemm@main git+https://github.com/shawntan/scattermoe.git@0526612bd53f3fb4dc3418eaa2876c89efe5e4e2