# bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_1e-8_same_format_ctx1_43b_64_3e-7
# bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_1e-8_same_format_ctx1_43b_64_3e-7

# bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_1e-8_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7
# bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_1e-8_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7


# bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_no_long_1e-8_same_format_ctx1_43b_64_3e-7
# bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_no_long_1e-8_same_format_ctx1_43b_64_3e-7


# bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 4500 5
# bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 0 250 4500 5


bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 0 250 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh nq 43b greedy test 0 200 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 0 250 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh nv_benefits_dragon_retriever300_retrieved_generic 43b greedy test 0 250 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 0 250 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh Iternal_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 4500 5 true



bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_1e-8_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_1e-8_same_format_ctx1_43b_64_3e-7 true

bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_1e-8_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_1e-8_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true


bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_no_long_1e-8_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv2_gpt_no_long_1e-8_same_format_ctx1_43b_64_3e-7 true


bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft.sh nq 43b greedy test 0 200 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv2_gpt_1e-8_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv2_gpt_1e-8_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv2_gpt_no_long_1e-8_same_format_ctx1_43b_64_3e-7 true


bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv3_gpt_1e-8_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv3_gpt_1e-8_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_same_format_ctx1_43b_64_3e-7 true


bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv3_gpt_1e-8_format_v2_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv3_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_format_v2_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_format_v2_same_format_ctx1_43b_64_3e-7 true


bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv3_gpt_1e-8_format_v3_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv3_gpt_1e-8_format_v3_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_format_v3_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_format_v3_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_format_v3_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_format_v3_same_format_ctx1_43b_64_3e-7 true

bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh nq 43b greedy test  0 200 4500 5 qa_blendv3_gpt_1e-8_conv_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh nq 43b greedy test  0 200 4500 5 qa_blendv3_gpt_1e-8_conv_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_conv_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_conv_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_conv_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv3_gpt_1e-8_conv_same_format_ctx1_43b_64_3e-7 true



bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv5_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv6_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv7_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true


bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv5_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv5_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv6_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv6_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv7_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv7_gpt_1e-8_format_v2_unbiased_cuckoo_pp1_same_format_ctx1_43b_64_3e-7 true


bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv8_gpt_1e-8_format_v2_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv8_gpt_1e-8_format_v2_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv8_gpt_1e-8_format_v2_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh nq 43b greedy test  0 200 4500 5 qa_blendv9_gpt_1e-8_format_v2_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv9_gpt_1e-8_format_v2_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv9_gpt_1e-8_format_v2_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true

bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh nq 43b greedy test 0 200 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 0 250 4500 5 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 4500 5 true

bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_zeroshot_sft_conv.sh dropbox_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 4500 5 true

bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh nq 43b greedy test  0 200 4500 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh nq 43b greedy test  0 200 4500 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 4500 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 4500 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 0 250 4500 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 0 250 4500 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 4500 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 4500 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 0 250 4500 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 0 250 4500 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true


bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh nq 43b greedy test  0 200 15000 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 15000 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 15000 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh nq 43b greedy test  0 200 15000 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh att_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test  0 250 15000 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test  0 250 15000 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 0 250 15000 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh inference_input_retriever_dragon_msmarcominilm_doc2dial 43b greedy test 0 250 15000 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 15000 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh NVIT_dragon_retriever_msmarcominilm_reranker_chunkbysents300_retrieved 43b greedy test 0 250 15000 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 0 250 15000 5 qa_blendv10_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
bash examples/foundational_qa/generate_multijob_ckpt_step_same_format_cross_fqa_conv.sh landrover_plus_benz_clean_plus_ford_tasb_ftmsmarcominilm_chunkbysents150_benzlandroverford_retrieved 43b greedy test 0 250 15000 5 qa_blendv11_gpt_1e-8_conv_quiet_cockatoo_pp1_same_format_ctx1_43b_64_3e-7 true
